---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600
        
    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes

    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

    - name: remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes

    - name: "install python for Ansible."
      become: yes
      apt:
        name: ["python3"]
        state: latest
        update_cache: yes

  roles:
    - configure-server