- name: "Copy backend files to server."
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "Start PM2"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start